name: kernel_json_serialization
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'
  kernel: any
  front_end: any
  args: any
  yaml: any
  _fe_analyzer_shared: any
  git: ^1.0.1
  http: ^0.12.2

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0

dependency_overrides:
  # kernel: may override by dependency
